intrinsics_path: pickafresa_vision/camera_calibration/calib_cg_21x_20251020_122431.yaml
model_path: pickafresa_vision/models/18k_oct19_yolo11_70x.pt
dataset_path: pickafresa_vision/datasets/yea_strawberry_class_2dbbox_aggr.v2-18k_3class_2dmixed_640p.yolov11
target_class: 'ripe'
confidence: 0.6
depth_window: 5
min_valid_depth_samples: 3
resolution:
- 640
- 480
fps: 30
